WHY USE NUMPY?

-Numpy provides efficient storage

-Provides better ways of handling data for processing

-Fast, easy to learn

-Uses relatively less memory to store data

In [1]:
import numpy as np

# Basics

In [2]:
#One dimensional
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,0])

print(a)
print(b)

print( )

#Two dimensional
c = np.array([[1,2,3],[6,7,8]])
print(c)

[1 2 3 4 5]
[6 7 8 9 0]

[[1 2 3]
 [6 7 8]]


In [3]:
#2D array #use 8 bit integer
myarr = np.array([[1,2,3333333,4,5]], np.int8)          
myarr

array([[  1,   2, -43,   4,   5]], dtype=int8)

In [4]:
myarr[0, 2]

-43

In [5]:
#Get Shape
myarr.shape

(1, 5)

In [6]:
#Get Type
myarr.dtype

dtype('int8')

In [7]:
#Get dimension
print(a.ndim)

print(c.ndim)

1
2


In [8]:
#Get size (in bytes)
a.itemsize

4

In [9]:
#Get number of elements
a.size

5

In [10]:
#Get Total size  (a.nbytes = a.itemsize * a.size)
a.nbytes

20

# Initializing Different Types Of Arrays

In [11]:
#All 0s matrix

zeros = np.zeros((2,5))
print(zeros)
print(zeros.shape)
print(zeros.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2, 5)
float64


In [12]:
#All 1s matrix

np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
#Any other number

#2 by 2 with 11

np.full((2,2), 11)

array([[11, 11],
       [11, 11]])

In [14]:
#Size similar to any other already existing array

np.full_like(a, 4) 


#OR


np.full(a.shape, 4)

#(Both give same result)

array([4, 4, 4, 4, 4])

In [15]:
#0 to n-1 numpy array
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
print(rng.reshape(3, 5))  #3X5 = 15
rng                       #no change / only reshapes

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
rng = rng.reshape(3, 5)
rng                     #original array changes

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
#retain old shape
rng = rng.ravel()
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
#gives 12 linearly spaced elements between  1 and 5 
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
#gives an empty array with any random elements
emp = np.empty((2,4))
emp

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.99596955e-321, 3.44899350e-307,
        4.22790516e-307]])

In [21]:
#copies the size of previously existing array and creates a new one with same size
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
ide = np.identity(5)     #5X5 identity matrix
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
ide.shape

(5, 5)

In [24]:
#Random Decimal Numbers Array

np.random.rand(4,2)

array([[0.76129451, 0.18219984],
       [0.29002859, 0.98304032],
       [0.17055281, 0.56887006],
       [0.28513969, 0.05528543]])

In [25]:
#Random Integer Numbers Array

np.random.randint(10, size=(3,3))       #less than 7

array([[8, 1, 4],
       [7, 1, 8],
       [5, 4, 0]])

In [26]:
np.random.randint(5,10, size=(3,3))    #between 5 and 10

array([[9, 9, 5],
       [8, 9, 9],
       [8, 5, 8]])

In [27]:
np.random.randint(-5,10, size=(3,3))    #between -5 and 10

array([[ 7, -3,  2],
       [ 0,  6,  5],
       [-2,  7,  3]])

In [28]:
#Repeat Array Elements

#Axis = 0 ... when 1D array
#Axis = 0 OR Axis = 1 ... when 2D array

arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis=0)

r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [29]:
arr2 = np.array([[1,2,3]])
r2 = np.repeat(arr2, 3, axis=0)
r3 = np.repeat(arr2, 3, axis=1)

print(r2)
print()
print(r3)

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 1 1 2 2 2 3 3 3]]


# Problem #1

""" 
Build array : 
 1 1 1 1 1
 1 0 0 0 1
 1 0 9 0 1
 1 0 0 0 1
 1 1 1 1 1
"""

In [30]:
output = np.ones([5,5], np.int8)
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [31]:
z = np.zeros([3,3], np.int8)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [32]:
z[1,1] = 9
z

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int8)

In [33]:
#Replace

output[1:4, 1:4] = z        #i.e For row,column : from 1st element to 3rd element(4 is exclusive) 
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

# Copying Arrays

# Copy type #1

In [34]:
x = np.array([1,2,3])
y = x 
#x and y references to the same array ... hence, any changes in y will be reflected in x

y

array([1, 2, 3])

In [35]:
y[2] = 10
y

array([ 1,  2, 10])

In [36]:
x     
#x has also changed

array([ 1,  2, 10])

# Copy type #2

In [37]:
z = x.copy()
print(z)

z[2] = 20
print(z)

[ 1  2 10]
[ 1  2 20]


In [38]:
x
#x doesn't change

array([ 1,  2, 10])

# Mathematics

In [39]:
m = np.array([1,2,3,4])
m

array([1, 2, 3, 4])

In [40]:
m + 2

array([3, 4, 5, 6])

In [41]:
m - 2

array([-1,  0,  1,  2])

In [42]:
m * 2

array([2, 4, 6, 8])

In [43]:
m / 2

array([0.5, 1. , 1.5, 2. ])

In [44]:
m += 2
m

array([3, 4, 5, 6])

In [45]:
n = np.array([1,0,1,0])

m + n

array([4, 4, 6, 6])

In [46]:
m ** 2   #square each element

array([ 9, 16, 25, 36], dtype=int32)

In [47]:
#Take the sin

np.sin(m)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

# Linear Algebra

In [48]:
#Matrix multiplication

a = np.ones([2,3])
print(a)

b = np.full([3,2], 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [49]:
#Linear determinant of identity matrix in '1'

c = np.identity(3)
np.linalg.det(c)

1.0

In [50]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [51]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.min(stats)

1

In [53]:
np.min(stats, axis=1)    #along columns

array([1, 4])

In [54]:
np.min(stats, axis=0)    #along rows

array([1, 2, 3])

In [55]:
np.max(stats)

6

In [56]:
np.sum(stats)

21

In [57]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [58]:
np.sum(stats, axis=1)

array([ 6, 15])

In [59]:
# Vertically Stacking Vector

v1 = np.array([2,4,6,8,10])
v2 = np.array([4,6,8,10,12])

np.vstack([v1, v2])

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12]])

In [60]:
np.vstack([v1, v2, v1, v2])

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12]])

In [61]:
np.hstack([v1, v2])

array([ 2,  4,  6,  8, 10,  4,  6,  8, 10, 12])

# Load data from file

In [62]:
filedata = np.genfromtxt('data.txt',  delimiter = ',')
filedata

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [63]:
#convert to int

filedata = filedata.astype('int32')
filedata

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Boolean Masking and Advanced texting

In [64]:
filedata > 7

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True])

In [65]:
filedata[filedata >= 7]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [66]:
#Index with a list in numpy
filedata[[1,3,5]]

array([2, 4, 6])